import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './styles/globals.css';
import './styles/animations.css';
import { UpdateProductModal } from '@/components/modals/UpdateProductModal';
import { DeleteProductModal } from '@/components/modals/DeleteProductModal';
import { AddCommodityModal } from '@/components/modals/AddCommodityModal';
import { ModalsProvider } from '@/contexts/ModalsProvider';
import { AddProductModal } from '@/components/modals/AddProductModal';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ModalsProvider>
          <UpdateProductModal />
          <DeleteProductModal />
          <AddProductModal/>
          <AddCommodityModal />
          <div>{children}</div>
        </ModalsProvider>
      </body>
    </html>
  );
}
